baseURL = 'https://sbee1031.github.io/docs'
locale = 'ko'
title = 'sbl'
theme = 'hextra'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  description = 'All Documents here!'
  ShowReadingTime = true
  ShowToc = true
  TocOpen = true
  mainsections = []

  [params.label]
    text = "My Docs"

[taxonomies]
  category = 'categories'
  tag = 'tags'

[frontmatter]
  draft = false
